Feature/cadastro novo usuario
willsantos0/nosso-mercado-livre pull request #1
Opened 2020-04-28 14:11 UTC by willsantos0

- Cadastro de novo usuário
- Não podemos ter dois usuários com o mesmo email.

Tive um problema no git e perdi os históricos de commit.

2020-04-28 21:18 UTC, asouza requested changes
Espero que não fique bravo comigo. Precisamos reduzir muito esse código e deixar ele suficiente para o que foi pedido na feature.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Application/Controllers/Base/BaseController.cs
> +    public class BaseController : ControllerBase
Opa, para que serve essa classe?

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Application/Controllers/UserController.cs
> +        private readonly IUserService _userService;
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho.* + 

*A complicação do nosso é código é proporcional a complicação da nossa feature. Quanto mais simples, melhor.* 

Toda indireção que você cria no seu código deixa-o um pouco mais complicado de entender. A regra básica é: toda classe nova deixa o código mais complicado. Então o que eu estou ganhando quando crio essa classe? Essa é a pergunta que você deve se fazer. O que seu código ganha criando essa interface Service? Pq o controller fica mais complicado chamando um repository em vez de chamar um service? Sobre ter uma interface eu fico de mãos amarradas pq sei que o mecanismo de injeção obriga você você a criar. 

Minha sugestão é remover :).

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Application/Controllers/UserController.cs
> +            catch (ValidationException ex)
Pq temos essas exceptions aqui? Pq daria uma exception de validação?

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Application/Controllers/UserController.cs
> +        public async Task<IActionResult> Update([FromBody]UserUpdateRequest user)
Opa, o update eu vou deixar de lado na revisão por enquanto, tudo bem? Já que não foi pedido na feature.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Application/Controllers/UserController.cs
> +        public async Task<IActionResult> GetAll()
vou deixar de lado também.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Application/Controllers/UserController.cs
> +        public async Task<IActionResult> GetById(long id)
deixando de lado

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Application/Controllers/UserController.cs
> +                throw ex;
Qual exception pode dar aqui? E se der, por que você simplesmente não deixa estourar? Pergunto isso porque tanto o tratamento de exception para validação quanto esse não acrescentam nada além de dificuldade de entendimento do código :). Cada branch do seu código aumenta um ponto no entendimento.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Const/Policy.cs
> +    public class Policy
Isso aqui é usado onde? Nas classes de configuração?

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Const/UserProfileConst.cs
> +    public class UserProfileConst
Para que temos isso? Nao temos regras de acesso ainda.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Entities/Base/BaseEntity.cs
> +    public abstract class BaseEntity
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho*

Toda abstração aumenta a dificuldade de entendimento do sistema. Quando você cria uma hierarquia  de classes, a pergunta que precisa fazer é? O que eu ganho de volta? Neste caso aqui. Tem algum lugar do sistema que você usa polimorfismo? Eu não especifiquei que um usuário precisa de data de atualização por exemplo. E em relação ao CreatedDate eu pedi que você o momento da criação, ou seja não é opcional para a api tentar definir ele com um valor diferente.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Entities/Base/BaseEntity.cs
> +        public virtual long Id { get; set; }
*Idealmente, todo código escrito deveria ser chamado por alguém. Se não tem ninguém chamando, ele não deveria existir.*

Neste momento nao precisamos acessar e nem alterar parcialmente nenhuma dessas informações. Não precisamos de get/set.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Entities/ProfileEntity.cs
> +    public class ProfileEntity : BaseEntity
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho*

Mesma explicação sobre a BaseEntity, aqui ainda mais profundo, pq você tem dois níveis de hierarquia. Ou seja toda classe que herdar aqui já nasce com 2 pontos de dificuldade a mais.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Entities/ProfileEntity.cs
> +    public class ProfileEntity : BaseEntity
Sugiro remover, assim como a BaseEntity.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Entities/UserEntity.cs
> +        public UserEntity()
*Deixamos pistas que facilitem o uso do código onde não conseguimos resolver com compilação.*

Aqui você não quer que ninguem chame e imagino que ele só exista por conta de framework. Aí você pode deixar uma dica dizendo que ninguém deve usar.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Entities/UserEntity.cs
> +        public UserEntity(UserUpdateRequest userUpdate, UserEntity userEntity)
*A complicação do nosso é código é proporcional a complicação da nossa feature. Quanto mais simples, melhor.*

O usuário tem um login e uma senha :). O id aqui não é informação natural, a não ser que você use o login. Se a infromação não é natural, ela nunca entra pelo construtor. Imagino que sela seja auto gerado na hora de registrar no banco.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Entities/UserEntity.cs
> +        public string FullName { get; set; }
*Idealmente, todo código escrito deveria ser chamado por alguém. Se não tem ninguém chamando, ele não deveria existir.*

Só temos login e senha e ainda não precisamos recuperar nem alterar parcialmente nenhuma das informações.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Entities/UserProfileEntity.cs
> +    public class UserProfileEntity : BaseEntity
Ainda não precisamos dessa abstração :).

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Enums/Exceptions.cs
> +    public enum Exceptions
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho* 
+
*Usamos tudo que conhecemos que está pronto. Só fazemos código do zero se for estritamente necessário.*

Opa, as exceptions já existem na linguagem. Criar uma classe que mapeia, usando um tipo primitivo, vai inclusive contra a ideia da linguagem de mapear os possíveis casos com tipos ricos. Além de aumentar a dificuldade de entendimento do sistema, por conta de uma classe que tenta fazer o que já está feito.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Interfaces/Repositories/IProfileRepository.cs
> +    public interface IProfileRepository : IRepository<ProfileEntity>
Como a gente ainda não precisa, sugiro remover.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Interfaces/Repositories/IRepository.cs
> +    public interface IRepository<T> where T : BaseEntity
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho*

Aqui é uma abstração a mais, não necessária no momento e implementada dentro do sistema, é super frágil. Vários métodos não necessários para todos os contextos e métodos super genéricos que também aumentam a complicação do código. Sugiro remover.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Interfaces/Repositories/IUserProfileRepository.cs
> +    public interface IUserProfileRepository : IRepository<UserProfileEntity>
Sugiro remover :)

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Interfaces/Repositories/IUserRepository.cs
> +    public interface IUserRepository : IRepository<UserEntity>
Sugiro remover a interface mãe e definir o único método necessário, save.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Interfaces/Services/IProfileService.cs
> +    public interface IProfileService : IService<ProfileRequest, ProfileResponse, Domain.Entities.ProfileEntity>
Sugiro remover :)

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Interfaces/Services/IService.cs
> +    public interface IService<T, R, E> where T : BaseRequest
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho*

Como falei lá em cima, o service aqui é uma indireção que não acrescenta nada no código. Deixa ele mais complicada e não dá nada em retorno.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Interfaces/Services/IUserProfileService.cs
> +namespace NossoMercadoLivreAPI.Domain.Interfaces.Services
Sugiro remover, pela mesma explicação de service dada acima.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Interfaces/Services/IUserService.cs
> +    public interface IUserService : IService<UserRequest, UserResponse, UserEntity>
Sugiro remover, pela mesma explicação de service dada acima.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Interfaces/UnitOfWork/IUnitOfWork.cs
> +    public interface IUnitOfWork
*Usamos tudo que conhecemos que está pronto. Só fazemos código do zero se for estritamente necessário.*

Algo similar deve ser possível através do orm e já deve estar pronto. Sugiro remover.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Request/Base/BaseRequest.cs
> +    public abstract class BaseRequest
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho*

Um objeto de request é super específico, não precisamos de generalização. Toda generalização deixa o código mais complicado e devemos fazer só quando for estritamente necessário, o que não é o caso aqui.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Request/ProfileRequest.cs
> +    public class ProfileRequest : BaseRequest
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho*

Um objeto de request é super específico, não precisamos de generalização. Toda generalização deixa o código mais complicado e devemos fazer só quando for estritamente necessário, o que não é o caso aqui.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Request/UserProfileRequest.cs
> +    public class UserProfileRequest : BaseRequest
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho*

Um objeto de request é super específico, não precisamos de generalização. Toda generalização deixa o código mais complicado e devemos fazer só quando for estritamente necessário, o que não é o caso aqui. 

Lembrando que o único objeto de request é o que recebe um login e senha.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Request/UserRequest.cs
> +    public class UserRequest : BaseRequest
Vamos deixar só com o que precisa e tirar a herança.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Request/UserUpdateRequest.cs
> +    public class UserUpdateRequest : BaseRequest
sugiro remover

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Response/Base/BaseResponse.cs
> +    public abstract class BaseResponse
sugiro remover pelos motivos explicados acima.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Response/ProfileResponse.cs
> +    public class ProfileResponse : BaseResponse
sugiro remover pelos motivos já explicados

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Response/UserProfileResponse.cs
> +    public class UserProfileResponse : BaseResponse
sugiro remover pelos motivos já explicados.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Response/UserResponse.cs
> +    public class UserResponse : BaseResponse
precisamos só retornar 200 por enquanto, pode ser vázio.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Infra.Data/Context/ContextDb.cs
> +    public class ContextDb : DbContext
*A complicação do nosso é código é proporcional a complicação da nossa feature. Quanto mais simples, melhor.*

Sugiro remover e usar o DbContext direto.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Infra.Data/Context/ContextDb.cs
> +    public class ContextDb : DbContext
Ou só deixar com o código estritamente necessário para a feature.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Infra.Data/Context/DbInitializer.cs
> +    public class DbInitializer
Mantém só o códgo estritamente necessário.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Infra.Data/Repository/Base/BaseRepository.cs
> +    public class BaseRepository<T> : IRepository<T> where T : BaseEntity
Por conta da complexidade adicionada e explicada nos comentários anteriores, eu sugiro remover também.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Infra.Data/Repository/ProfileRepository.cs
> +    public class ProfileRepository : BaseRepository<ProfileEntity>, IProfileRepository
sugiro remover

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Infra.Data/Repository/UserProfileRepository.cs
> +    public class UserProfileRepository : BaseRepository<UserProfileEntity>, IUserProfileRepository
sugiro remover

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Infra.Data/Repository/UserRepository.cs
> +    public class UserRepository : BaseRepository<UserEntity>, IUserRepository
*A complicação do nosso é código é proporcional a complicação da nossa feature. Quanto mais simples, melhor.*
Sugiro só manter a interface pq conta da obrigatoriedade do framework e deixar só o método de inserir.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Infra.Data/UnitOfWork/UnitOfWork.cs
> +    public class UnitOfWork : IUnitOfWork
*Usamos tudo que conhecemos que está pronto. Só fazemos código do zero se for estritamente necessário.*

Como isso já é pronto pelo framework, eu sugiro remover.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Service/Common/Util.cs
> +        public static string GetSha256Hash(SHA256 shaHash, string input)
Não tem geração de hash pronto em algum dos frameworks utilizados no projeto?

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Service/Exceptions/AppException.cs
> +    public class AppException : Exception
*Usamos tudo que conhecemos que está pronto. Só fazemos código do zero se for estritamente necessário.*

Provavelmente já tem exception pronta para tudo que você vai precisar no código. Sugiro remover

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Service/Exceptions/CustomExceptionFilter.cs
> +    public class CustomExceptionFilter : IExceptionFilter
*A complicação do nosso é código é proporcional a complicação da nossa feature. Quanto mais simples, melhor.*

Essa classe parece fazer sentido para controlar como os problemas vão ser retornados, deixa só o necessário, tudo bem? Não tem algo pronto para isso?

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Service/Exceptions/CustomExceptionFilter.cs
> +        private HttpStatusCode GetErrorCode(Type exceptionType)
*A complicação do nosso é código é proporcional a complicação da nossa feature. Quanto mais simples, melhor.*

Aqui não precisamos, já que não temos as situações. Mesmo se tivesse, a gente ia ter que arrumar um jeito de diminuir a carga cognitiva desse código.

2020-04-28 21:18 UTC, asouza commented on src/NossoMercadoLivreAPI.Service/Exceptions/ForbiddenException.cs
> +    public class ForbiddenException : Exception
Sugiro remover todas as exceptions customizadas. Elas geralmente só trazem indireção e não acrescentam nada que já não possa ser expressado pelas exceptions prontas da linguagem.

2020-04-28 21:36 UTC, willsantos0 commented on src/NossoMercadoLivreAPI.Application/Controllers/Base/BaseController.cs
> +    public class BaseController : ControllerBase
Essa classe serve basicamente para habilitar o cors da aplicação, caso algum front-end esteja querendo acessar, e colocando apenas nesse controller eu já habilito para todos os outros controllers. Irei remover, pq no momento acho que não vai ser necessário isso.

Desculpa por tanto código. Acabo que eu animo e começo a escrever sem parar kkkk. Vou remover tudo que não for usado.

2020-04-29 10:12 UTC, asouza commented on src/NossoMercadoLivreAPI.Application/Controllers/Base/BaseController.cs
> +    public class BaseController : ControllerBase
Tudo bem :). Fico feliz que você não tenha ficado bravo :)

2020-04-29 17:53 UTC, asouza requested changes
Concentrei o review no controller por enquanto :)

2020-04-29 17:53 UTC, asouza commented on src/NossoMercadoLivreAPI.Application/Controllers/UserController.cs
> +        public UserController(IValidator<UserRequest> validator)
*Usamos tudo que conhecemos que está pronto. Só fazemos código do zero se for estritamente necessário.*
+
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho.*

Pq temos uma interface com uma implementação se a validação através de atributos/annotations/decorators na ViewModel já funciona por padrão? Você anota lá e usa o ModelState para verificar.  Isso aumenta a dificuldade de entendimento do sistema e não parece trazer nenhuma vantagem para compensar :).

2020-04-29 17:53 UTC, asouza commented on src/NossoMercadoLivreAPI.Application/Controllers/UserController.cs
> +                    var userEntity = await userRepository.GetOneByFilterAsync(u => u.Email == user.Email);
*Não retornamos nulo dentro das regras da aplicação. Pense que seu computador vai explodir.*

Um método que diz que vai retornar algo, precisa retornar. Caso contrário o ponto do código que usa aquele método tem que ficar fazendo !=null o tempo todo e aí uma hora, quando não fizer, vai tomar NPE. Na última versão  do c# já tem suporte para retorno opcional.

2020-04-29 17:53 UTC, asouza commented on src/NossoMercadoLivreAPI.Application/Controllers/UserController.cs
> +                    var userEntity = await userRepository.GetOneByFilterAsync(u => u.Email == user.Email);
Ah, tem mais uma coisa. Não precisamos dessa verificação ainda, a verificação de email é a próxima funcionalidade.

2020-04-29 17:53 UTC, asouza commented on src/NossoMercadoLivreAPI.Application/Controllers/UserController.cs
> +                    UserEntity userSave = new UserEntity(user);
A classe User representa um conceito importante do negócio, que é o usuário. O usuário não chama UserEntity :).

2020-04-29 17:53 UTC, asouza commented on src/NossoMercadoLivreAPI.Application/Controllers/UserController.cs
>              catch (Exception ex)
não precisa tratar exception aqui. Caso algum erro aconteça, um 500 vai ser retornado. E é o que faz sentido, já que é um erro inesperado mesmo.

2020-04-29 22:31 UTC, asouza requested changes
Agora o código ta ficando proporcional a feature :).

2020-04-29 22:31 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Validators/ValidateModelStateAttribute.cs
> +    public class ValidateModelStateAttribute : ActionFilterAttribute
Esse código precisa mesmo? Estou apenas curioso porque, pelo que vi no código de Raimundo, não vi essa configuração extra e mesmo a validação era feita e 400 retornado com o json de erros. Será que perdi algo? 

A pergunta é só para a gente conseguir o código necessário :).

2020-04-29 22:31 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Entities/User.cs
> +        public User(long id, string fullName, string email, string document, string phoneNumber, string password)
*A versão mais eficiente de uma pessoa programando é aquela que questiona e implementa estritamente o que foi descrito. Não inventamos coisas que não foram pedidas, não fazemos suposição de funcionalidade e nem caímos na armadilha de achar que entendemos mais do que a pessoa que solicitou a funcionalidade.*

Opa, vamos reduzir aqui também. O usuário tem login e senha no momento :).

2020-04-30 17:34 UTC, asouza requested changes

2020-04-30 17:34 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Entities/User.cs
> +        public User(long id, string email, string password)
O id aqui não é informação natural do objeto. O que não é natural, não entra pelo construtor :). O id aqui é autogerado na hora do insert.

2020-04-30 17:34 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Request/UserRequest.cs
>          public long Id { get; set; }
O id pode deixar definido pelo banco... se a informação não está na necessidade da funcionalidade, pode considerar que ela não é provida pelo usuário.

2020-04-30 17:34 UTC, asouza commented on src/NossoMercadoLivreAPI.Application/Controllers/UserController.cs
> +            User userSave = new User(user);
*Deixamos pistas que facilitem o uso do código onde não conseguimos resolver com compilação.*

O construtor do seu user diz que tem um argumento chamado password do tipo String. Como que esse ponto do código sabe que precisa encodar? E se dentro do construtor do User a senha fosse encodada de novo? Que tipo de sinal você poderia deixar para explicar que a senha precisa chegar encodada?

2020-05-04 14:13 UTC, asouza requested changes

2020-05-04 14:13 UTC, asouza commented on src/NossoMercadoLivreAPI.Application/Controllers/UserController.cs
> +        /// Salva Usuário. O campo password deve ser passado sem criptografia. A criptografia é gerada ao inserir usuário.
Opa, deixa o comentário perto do uso, que é no construtor do user. O seu comentário pode ser apenas declarativo, sem falar detalhes de implementação. Justamente para ele conseguir viver por mais tempo no sistema e não precisar ser alterado quando você trocar o código .

2020-05-04 16:11 UTC, asouza requested changes
Últimas perguntas e acho que com a solução a gente fecha :)

2020-05-04 16:11 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Entities/User.cs
>          public User(UserRequest userRequest)
Pq tem dois construtores?

2020-05-04 16:11 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Entities/User.cs
>          public User()
Pq tem um construtor sem argumentos?

2020-05-04 16:24 UTC, willsantos0 commented on src/NossoMercadoLivreAPI.Domain/Entities/User.cs
>          public User()
Esse construtor era por conta do EF. Quando o banco era criado dava o erro InvalidOperationException referente ao construtor. Mas aparentemente alguma coisa que eu alterei arrumou esse erro. Quinta deu o mesmo problema com o raimundo.
Irei remover.

2020-05-04 16:25 UTC, willsantos0 commented on src/NossoMercadoLivreAPI.Domain/Entities/User.cs
>          public User(UserRequest userRequest)
O segundo construtor era por conta da população do banco que eu fazia para os meus testes locais aqui.
Irei remover.

2020-05-04 23:55 UTC, asouza approved these changes
Boaaa!!!

2020-05-04 23:55 UTC, asouza commented on src/NossoMercadoLivreAPI.Domain/Entities/User.cs
>              Password = BCrypt.Net.BCrypt.HashPassword(userRequest.Password);
Ah, uma observação importante aqui. Talvez alguém critique o fato de você receber um userRequest direto no seu construtor da classe que representa alguma coisa de modelo em si. Realmente foge um pouco da ideia de domain driven design mas eu, Alberto, não ligo :). Para mim está tudo bem... Só queria pontuar.

2020-05-05 00:09 UTC, merged